# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Add any additional linter rules here
    public_member_api_docs: true
    lines_longer_than_80_chars: false
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    prefer_const_constructors: true
    unnecessary_new: true
    avoid_print: true
    # Add more rules as needed for your project